apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |-
      - op: replace
        path: /spec/template/spec/nodeName
        value: '{{.Name}}-control-plane'
      - op: replace
        path: /spec/template/spec/hostNetwork
        value: true
    target:
      kind: Deployment
images:
  - name: registry.k8s.io/kwok/kwok
    newTag: '{{.KwokControllerImageTag}}'
    newName: '{{.KwokControllerImageName}}'

resources:
  - ../../../../kustomize/kwok
